format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green)$directory$rust$package$python
[â””â”€>](bold green) """

[python]
format = '[${symbol}(${version})]($style)'
symbol = "ğŸ "
style = "bold yellow"
pyenv_version_name = true
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "setup.py"]
